---
title: "Examining The Roots of Environmental Injustice in Minneapolis"
author: "Na Nguyen"
format: 
  html:
    page-layout: full
---

This interactive dashboard shows the legacy of residential segregation, one that has led to stark environmental injustice that tremendously ails Black, Latino, and Native American families in Minneapolis. 

The correlation between climate change effects and marginalized neighborhoods are **apparent**: *the more socially vulnerable a neighborhood is, the more exposed they are to the effects of climate change---and we can trace this back to residential seggregation practices from the early 20th century.* 

The Social Vulnerability Index is an index score released by the CDC that utilizes a variety of survey variables to highlight communities' social vulnerability, which is defined as "certain social conditions, including high poverty, low percentage of vehicle access, or crowded households, among others, may affect that community’s ability to prevent human suffering and financial loss in the event of a disaster." [cite SVI documentation] A linear model of the impact of historical redlining grades on the SVI score of Minneapolis census tracts shows the following predicted SVI results, with significant p-values (SVI scores are in a percentile range from 0 to 1, with 1 the most vulnerable:

 - A ("Best"): 0.25683
 - B ("Still Desirable"): 0.48408
 - C ("Definitely Declining"): 0.84779
 - D ("Hazardous"): 0.73834

Neighborhoods given grades of C and D - almost always neighborhoods mostly populated by people of color - clearly still face the adverse consequences of redlining and similar practices in the form of increased vulnerability to climate disasters and other soicioeconomic issues today.

<iframe src="https://opbfa1-anh-nguyen.shinyapps.io/msp_enviro_no_title/" style="width: 90%; height: 920px;display: block; margin-left: auto; margin-right: auto; ">

</iframe>
